# Generated by Django 4.0.4 on 2023-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_newslatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslatter',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
