# Generated by Django 4.0.4 on 2023-04-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
